@startmindmap "LLM Engineering Landscape"

<style>
    mindmapDiagram {
        .top-section {
            Padding 12
            Margin 6
            HorizontalAlignment left
            LineColor green
            LineThickness 3.0
            BackgroundColor lightgreen
            RoundCorner 20
            MinimumWidth 200
        }
        .level-1-section {
            Padding 12
            Margin 6
            HorizontalAlignment center
            LineColor blue
            LineThickness 3.0
            BackgroundColor lightblue
            RoundCorner 20
            MinimumWidth 150
        }
        arrow {
            LineStyle 1
            LineThickness 0.5
            LineColor green
        }
    }
</style>

+ LLMs
++ **Local LLMs**\nOllama for Local LLM deployment. <<top-section>>
+++_ Jupyter Lab and Anaconda
+++_ VS Code and Virtual Environments
++++_ .env for API Keys
++ **Frontier Model LLMs**\nHigh powered. <<top-section>>
+++_ GTP (OpenAPI)
++++_ Strengths
+++_ Claude (Anthropic)
++++_ Strengths
+++++_ 3.5 sonnet has surpassed PHD in math, physics, chemistry
+++_ Gemini (Google)
++++_ Strengths
+++_ Llama
++++_ Strengths
++ **Limitations**\nMost LLMs are not at PHD level\n. <<top-section>>
+++ **Make mistakes**\nConfident in their hallucinations
+++ **Knowledge cut-off dates**\nAll have knowledge cut-off dates.
+++ **Inherent tokenization limitations**\nHow many times does "a" appear in this sentence?
+++ **Older LLMs were bad at doing calculations**\nGPT is making progress here

++ **Notes**\nRough notes that may\nor may not become pages\nin career or study. <<top-section>>
+++_ Chatbots
+++_ RAG
+++_ Web Page Summarizers <<level-1-section>>
++++_ LLAMA
+++_ Agentic AI Projects



' ++ **Career History**\nContent for interviews\nand CV. <<top-section>>
' +++_ Project Kanban Board
' +++_ Database
' +++_ Resources Page
' ++++_ Interview tips
' ++++_ Negotiations

' ++ **Study (Self Improvement)**\nOngoing strategic studies. <<top-section>>
' +++ Study Process  <<level-1-section>>
' ++++_ Effective note making
' ++++_ Summarized Study Process
' +++ Study Activity  <<level-1-section>>
' ++++ New Studies
' +++++_ **Kanban board**
' +++++_ Notes (InFocus)
' +++++_ Summaries
' +++++_ Queued
' +++++_ Trash (Can delete)
' ++++ Revision
' +++++_ Current (Priority)
' +++++_ Needs Attention
' +++++_ Strong understanding
' ++++ Roadmaps
' +++++_ Leetcode Roadmap
' +++ General Resources  <<level-1-section>>
' ++++ Problem solving approach
' ++++ Study Topics
' +++++_ Discrete Mathematics
' +++++_ Algorithms, Problem Solving, and Data Structures


@endmindmap

